# Generated by Django 3.1.3 on 2020-12-01 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('doneOn', models.DateTimeField(auto_now_add=True)),
                ('by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doneBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
